version: '3.8'

services:
  zetin-competition:
    image: node:20
    volumes:
      - ../:/workspace
    environment:
      - PATH_FILES=/workspace/.devcontainer/files
      - ADMIN_ID=admin
      - MONGODB_HOST=zetin-competition-db
    links:
      - zetin-competition-db
    command: sleep infinity

  zetin-competition-db:
    image: mongo:4.4.14
    volumes:
      - ./db:/data/db
